env:
  - "DB=mysql"
  - "DB=postgresql"
  global:
    - "JASMINE_PORT=8888"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake --trace fulcrum:setup db:setup"
rvm:
  - 1.9.3
  - 2.0.0
script:
  - "bundle exec travis"